### PR TITLE
Update Travel Fund for JS Interactive

### PR DESCRIPTION
**Pull request by codeekage**
Event: JS Interactive + Collaborator Summit
Location: Vancouver BC CAN
Traveling from: Lagos, Nigeria

I plan to attend Collaborator Summit and Code + Learn. In addition to participating in Collaborator Summit.

@nodejs/community-committee

Airline : $1900
Lodging: $600
Visa: $145

### CODE REVIEW

**Comment by codeekage** [comment]
:tada: :tada: :tada:

**Comment by codeekage** [comment]
This can be merged! @Trott

**Comment by Trott** [comment]
> This can be merged! @Trott

I'm not sure if the rules specify that updates need to stay open for 72 hours, but even if they don't, I prefer to leave them open that long just in case...

But if someone else comes along and merges this before then, that's fine by me.

**Comment by codeekage** [comment]
@Trott can you help merge this?

**Pull request merged**
