### PR TITLE
Update MEMBER_TRAVEL_FUND.md

### PR DESCRIPTION
**Pull request by namdeirf**
Updating directions for naming the file inorder to better process requests as they come in, etc. This is a request from the accounts team to so they can differentiate between requests easier.

Thank you

### CODE REVIEW

**Comment by namdeirf** [comment]
@ladyleet let me know if there is another protocol I should follow for a change in the instructions. Thank you

**Comment by ladyleet** [comment]
@namdeirf looks good to me too! :) this will def help with all the expenses that are currently coming in!

**Comment by ladyleet** [comment]
@mhdawson is this good to be merged?

**Comment by ladyleet** [comment]
@mhdawson @codeekage can this be merged?

**Comment by JemBijoux** [comment]
I think we're looking good, gonna land this @ladyleet.

**Pull request merged**
