### PR TITLE
Travel fund request for Collab Summit - @maddhruv

### PR DESCRIPTION
**Pull request by maddhruv**
Purpose: Attend **JS Interactive and Node Collab Summit**
Location: **Vancouver, BC CAN**
Travelling from: **Jaipur, IND**

Airfare - $1500
Lodging - $500
Ground Transportation and Food - $100

### CODE REVIEW

**Comment by maddhruv** [comment]
Any lights from the @nodejs/community-committee and @nodejs/tsc

**Comment by maddhruv** [comment]
@Trott the PR has been opened for :100: hours now!
There's no update with approvals or concerns.
Please look! :smile:

**Comment by Trott** [comment]
> the PR has been opened for 💯 hours now

Yeah, but TSC and CommComm pings are only 17 hours ago, so that's probably what's up there. :-D

**Comment by Trott** [comment]
Still needs one more approval each from @nodejs/tsc and @nodejs/community-committee

**Comment by Trott** [comment]
One more @nodejs/tsc approval needed.

A rebase to get rid of the conflict would be good, but that can happen at landing time too.

**Comment by maddhruv** [comment]
@Trott @mhdawson rebased!
can be merged?

**Comment by Trott** [comment]
Landed in 7164f101698486a5fc284db8b74a9f47ed949961

**Pull request closed without merging**
