### PR TITLE
Travel fund request for JS Interactive/Collab Summit 2018

### PR DESCRIPTION
**Pull request by codeekage**
Event: JS Interactive + Collaborator Summit
Location: Vancouver BC CAN
Traveling from: Lagos, Nigeria

In addition to participating in Collaborator Summit.
@nodejs/community-committee

~Registration: $350~
Airline: $1800.00
Lodging: $480

### CODE REVIEW

**Comment by mcollina** [comment]
I am -1 in covering for a ticket to the conference (and the hotel for those days). As most of us will go, it’s either all of us or no one. A criteria has to be determined.

+1 on everthing else.

**Comment by mcollina** [comment]
I've opened https://github.com/nodejs/admin/issues/158 to discuss.

**Comment by codeekage** [comment]
Have canceled out the registrations fees for JS Interactive 👍

**Comment by Trott** [comment]
Needs one more @nodejs/tsc approval.

**Comment by Trott** [comment]
I'm going to land this, but if you will have visa expenses too, you can feel free to open a PR to update to include those as well.

**Pull request merged**
