### PR TITLE
Travel Fund: Gus Caplan – TC39 Meeting

### PR DESCRIPTION
**Pull request by devsnek**
**Event:** TC39 meeting July 23rd - 27th 2018
**Event Location:** Redmond, WA, US
**Traveling From:** Chicago, IL, US
**Foundation member:** Yes

I've been invited as a guest to the July 2018 TC39 meeting. If I have a chance to speak up, hopefully I'll be able to represent my viewpoint as a Node.js collaborator.

|      Item        | Amount  |
| ---------------- | ------: |
| Ground transport |       US $50 |
| Flight           |   US $364.40 |
| Lodging          |   US $697.88 |
| **Total**        | US $1,112.28 |

### CODE REVIEW

**Comment by devsnek** [comment]
am i able to make changes to this number after it got approvals? just going through purchasing and it looks like the plane tickets went up to ~470.

**Comment by TimothyGu** [comment]
@devsnek Sure… I could dismiss the reviews made when the number is lower. Just make sure we all know when you're done editing.

**Comment by devsnek** [comment]
@Trott @TimothyGu final numbers are in, sorry about that

**Comment by joyeecheung** [comment]
@devsnek I think the current process is if you do not need the transfer before you book, you can allocate a bit more in the document here and come back adjusting the amount later when you have the invoices/tickets, and then send the actual request to the foundation staff.

**Comment by Trott** [comment]
Yeah, to echo what @joyeecheung said, feel free to ask for a small bit more than you think you'll need and then adjust down after-the-fact, once you know how much the actual cost is.

**Comment by Trott** [comment]
Also: Still LGTM.

**Comment by Trott** [comment]
I believe this still needs two @nodejs/community-committee approvals.

**Comment by Trott** [comment]
Still needs one more CommComm approval.

By the way, the list of people in CommComm at https://github.com/nodejs/community-committee does not match the membership of @nodejs/community-committee. (@codeekage is listed in the repo but not a member of the GitHub team.) If those two lists could be reconciled, that would be helpful.

**Comment by codeekage** [comment]
@Trott  the pull request for my membership is yet to be merged... but the membership and invitation to the github team has been done.

**Comment by codeekage** [comment]
@Trott I could help complete the approvals from the CommComm

**Comment by Trott** [comment]
Open for 72 hours, has 2 or more approvals from each of CommComm and TSC, and has no objections. This is approved and merged.

**Pull request merged**
