### PR TITLE
Travel Fund request: @jdalton for Node + JS Interactive 2019

### PR DESCRIPTION
**Pull request by jdalton**
## Attending Node+JS Interactive
Event: Node+JS Interactive
Event Location: Montreal QC, Canada
Traveling From: Seattle, WA
Doing: Possible participation in Foundation member project panel 
Stipend Size: $519
Foundation member: Yes
Corporate travel fund: None

### CODE REVIEW

**Comment by Trott** [comment]
How was the $519 derived? Is that airfare, hotel, both, something else?

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by jdalton** [comment]
That's airfare. American Airlines to destination and Canada Air back.

**Comment by brianwarner** [comment]
@jdalton, do you think you might be able to submit your expense reimbursement request by the end of this week? Thanks!

**Comment by jdalton** [comment]
Oh yes, sorry. Will do.

**Pull request merged**
