### PR TITLE
Travel fund request for Collaborator Summit in Berlin (@mgrybyk)

### PR DESCRIPTION
**Pull request by mgrybyk**
Collab Summit Travel
---
**Event**: Node.js Spring Collaborator's Summit (30 May - 31 May 2019)
**Event Location**: Berlin, Germany
**Traveling from**: Malaga, Spain
**Doing**: Attending

|  | Cost  |
|------|-----|
| Travel to Berlin | 26.10 € |
| Travel from Berlin | 85.67 € |
| Lodging | 208.80 € |
| **Total** | **320.57 €** |

[WebdriverIO](https://github.com/webdriverio/webdriverio) [TSC](https://github.com/orgs/webdriverio/teams/technical-steering-committee) member
Corporate funding is not available.

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by Trott** [comment]
This needs two approvals from @nodejs/tsc.

**Comment by joyeecheung** [comment]
@mgrybyk Are you coming as a collaborator of an OpenJS foundation project or are you coming as an ex-Node.js foundation individual member (but somehow you didn't get to added to the members team)?

Not sure if the details have been ironed out yet but are Node.js TSC and CommComm members supposed to approve travel fund requests from other OpenJS projects? cc @jorydotcom @MylesBorins

**Comment by Trott** [comment]
I'm adding this to the TSC agenda because @mgrybyk deserves a "yes, see you there" or a "no, sorry" quickly. I agree that approving this would violate the letter of the Travel Fund policy/procedure/whatever unless they're a Node.js Foundation member. If that's the end of it, we should say so quickly. If we're all comfortable with a "that's OK, it's the spirit that counts here" approval and/or changing the policy/procedure to accommodate these sorts of requests, we should also do that quickly. @nodejs/tsc

**Comment by mgrybyk** [comment]
@joyeecheung I'm a member of WebdriverIO TSC and only started my way on understanding how does the things work. I'd like to meet other WebdriverIO members, and besides of that participate in discussions, understand where my input maybe most efficient. 
Thank you

**Comment by jorydotcom** [comment]
@Trott @joyeecheung JSF projects were told that the travel fund would be available to them in the spirit of creating a collaborator summit for all projects - this was reiterated at the Bootstrap meetings and early summit planning meetings (@mcollina @MylesBorins  & @ladyleet can confirm).

**Comment by joyeecheung** [comment]
I guess the next step is to merge https://github.com/nodejs/admin/pull/363 (opened for more than 48 hours now) and then this?

**Comment by Trott** [comment]
> I guess the next step is to merge #363 (opened for more than 48 hours now) and then this?

Yes. I was waiting for 72 hours (which will be in another (5 hours or so from now) on #363. Then this can land right away if it has the right approvals. At least, that's what I'm comfortable with. Anyway, I'll remove this from the tsc-agenda and add my approval as it looks like this is going to be resolved today.

**Pull request merged**
