### PR TITLE
Require travel fund recipients to submit trip reports

### PR DESCRIPTION
**Pull request by joyeecheung**
This is a rough sketch of the idea proposed in https://github.com/nodejs/admin/issues/281 , I propose we start deploying this practice in the next summit.

I would like to have this landed at least before May. We could add more details and tips in later PRs, but I think it's fine to leave it vague for now, as people won't start writing reports after the May summit, by then we should have more details here e.g. a template, where the links of reports should reside (I am thinking about having them archived in a repo under this organization actually).

I intentionally did not leave any requirements for the format of the report, but only suggestions about the contents - people can be creative, e.g. they can even draw instead of writing, and the reports don't have to be written in English (if the requester comes from a non-English speaking country, writing reports in their native language would also help inspiring developers in their local community).

cc @nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by gireeshpunathil** [comment]
- this puts too much pressure on folks who use the fund IMO
 - isn't it (purpose of travel) something that needs to be ratified at the time of approval?
 - were there reported abuse of the fund?
 - how do one enforce a trip report? what happens if someone is not providing one?
 - what elements in the report will be used decide the travel was successful?
 - if one just attend all the sessions and meet many fellow collaborators, will it be deemed a poor participation?
 - are the guidelines or practices for validating a trip report? will that be foolproof?
 - will this process diminish the existing and established trust among the collaborators?

**Comment by mcollina** [comment]
One of the main purpuse of adding this is the lack of actionable material out of the travel fund. We know a lot of people traveled thanks to this, but we have info on what actually happened there. Having it would enable to promote Node and its community better.

I would remove the blocker on reimbursement. Essentially _not_ writing one could lead to not being able to access the travel fund again.

I would also add that it could be a couple of paragraphs long, and it would be awesome if it was published as a blog post.

**Comment by joyeecheung** [comment]
To be clear, this is not about misuse of the fund, it's about using process to justify expense instead of solely rely on personal trusts. As someone who can approve a request, I am very uncomfortable with the power to hand out money donated by someone I don't know to someone I don't know, so I simply refrain from approving any requests from people I do not know, or from people I know but unsure about their purpose of travel, and I think that choice is biased. Why should I give preference to a certain collaborator simply because I know them? (even though I know them from their work on GitHub but still there's personal relationship involved). However it would be much easier for me to approve a travel fund request from someone I don't know if we have a process like this in place.

The travel fund approval process is based on trust, and in principle I think trust should be based on process, instead of human being's instincts.

I won't be able to answer all the questions asked, because I am not an HR expert, this is not a proposal to improve efficiency, its intent is to create an environment where administrators can feel safer to approve travel fund requests, and new faces in the community can feel safer to submit requests. As someone who have been onboarding Node.js collaborators in the past years, I always make sure I inform new collaborators about this fund, but I can feel that it's hard for them to submit requests because they do not know how to justify the expense - and this PR provides an approach for that.

I can modify the PR to unmake this a requirement for subsequent requests and make the report a mere recommendation.

**Comment by addaleax** [comment]
> but I can feel that it's hard for them to submit requests because they do not know how to justify the expense (even when they are willing to travel) - and this PR provides an approach for that.

Independently of this PR, would it help if we set clearer guidelines for which kinds of travel are appropriate to ask for and which not? That would probably help both administrators and people who wish to use the travel fund.

**Comment by joyeecheung** [comment]
> Independently of this PR, would it help if we set clearer guidelines for which kinds of travel are appropriate to ask for and which not?

I think it would help, yes, but I am not sure how to write something clear enough. If we are being too restrictive in the types of travels and say something very specific like: "for example, travel to collaboration summit to talk about your recent patches in Node.js core.", then people would still wonder when their cases do not closely match any of the examples. If we are being too vague, then it's not clear. We could be clear about what kind of travel is inappropriate, though, for instance I personally think it's inappropriate to request funds if you do not have anything scheduled (e.g. an event) at the destination, or have something scheduled for your personal gains (e.g. an interview).

That's why I think having trip reports is a good start, from the report you can learn about what people normally use this fund for and what they do with very practical examples, but those reports should also be personal and unique enough so that it won't trap you into trying to match your own cases against those examples precisely.

**Comment by WaleedAshraf** [comment]
@joyeecheung thanks for the clarification. I agree with all the reasons you mentioned. Let's start with having it as a recommendation and see how many reports and what type of reports we get. Then we can later decide if it needs to a requirement for travel fund or not.

**Comment by keywordnew** [comment]
IMO a trip report (if not overly prescriptive) is not much of an imposition. If a person uses company funds to attend the Collab Summit, they typically make trip reports for their team anyway. For the project, it will be a new, possibly very helpful channel to share the effort needed to collect data for making future Collab Summits better 🚀

I would be +1 on sharing a template, but not requiring that folks use it. They will use it if it's helpful and makes the task easier.

**Comment by ladyleet** [comment]
Thx for the initiative @joyeecheung!

**Comment by mhdawson** [comment]
I'm +1 for adding the ask for a trip report.  Ideally something that is public (like a blog) and which relates some of the benefits from having used the travel fund.  I agree that it should not be a requirement for reimbursement but that it could be a factor in future approvals.  As mentioned it is common practice to require something similar for business travel and writing up a short report should not be too much of an ask in return for the travel funds.

We should acknowledge that people will have a different level of comfort with writing/language skills so the key thing in my mind is the there was an effort to do the write up and share it as opposed to the particular content or how polished it is.  Our wording should reflect that in order to try to remove any anxiety there might be on that front.

**Comment by joyeecheung** [comment]
I guess this can be merged now? We can fill in the details later.

> Our wording should reflect that in order to try to remove any anxiety there might be on that front.

Is the current wording suffice? I think just saying that `it's recommended to do something` already meets

> there was an effort to do the write up and share it as opposed to the particular content or how polished it is.

? (but I am not a native English speaker so correct me if I am wrong).

**Comment by joyeecheung** [comment]
I think this PR is ready to land? If you think the wording still needs to be changed before landing, please leave a comment in the next 48 hours.

**Pull request merged**
