### PR TITLE
Include discussions in moderation policy

### PR DESCRIPTION
**Pull request by tniessen**
Answers to discussions are comments, but discussions themselves do not fit the current definition of "Post".

### CODE REVIEW

**Review by Trott — APPROVED** [review]
LGTM. I'd also be OK with some "and similar GitHub features" wording.

**Review by targos — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by jasnell** [comment]
LGTM

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/moderation

**Review by richardlau — APPROVED** [review]

**Review by JohnTitor — APPROVED** [review]

**Review by RaisinTen — APPROVED** [review]

**Review by aduh95 — APPROVED** [review]

**Review by MylesBorins — APPROVED** [review]

**Review by jasnell — APPROVED** [review]

**Pull request merged**
