### PR TITLE
remove CommComm from Moderation Policy

### PR DESCRIPTION
**Pull request by Trott**
@nodejs/tsc @nodejs/moderation

### CODE REVIEW

**Review by richardlau — APPROVED** [review]

**Review by aduh95 — APPROVED** [review]

**Review by cjihrig — APPROVED** [review]

**Comment by benjamingr** [comment]
I feel like I've missed something :)?

**Review by benjamingr — APPROVED** [review]

**Review by JohnTitor — APPROVED** [review]

**Review by ljharb — APPROVED** [review]
for moderation

**Review by bnb — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by ryanmurakami — APPROVED** [review]

**Comment by benjamingr** [comment]
The README also needs an update here - and should the contents of this repo (in its entirety?) move to nodejs/tsc?

**Comment by Trott** [comment]
> The README also needs an update here - and should the contents of this repo (in its entirety?) move to nodejs/tsc?

Yes, many things need updates. The issue about what to do with the repo was raised elsewhere too. Can't find it right now. An argument for archiving and using TSC repo only in my opinion. Conversations get very fractured in the current 130-repositories-in-the-org-that-aren't-archived setup.

**Comment by Trott** [comment]
> Yes, many things need updates. The issue about what to do with the repo was raised elsewhere too. Can't find it right now. An argument for archiving and using TSC repo only in my opinion. Conversations get very fractured in the current 130-repositories-in-the-org-that-aren't-archived setup.

I'm interested in keeping the focus in this PR on the Moderation Policy because I want to propose changes to that policy. But this really needs to happen first IMO.

**Pull request merged**
