### PR TITLE
travel request for Eemeli Aro for Node + JS Interactive 2019 and Collab Summit

### PR DESCRIPTION
**Pull request by eemeli**
I'll be presenting on [The State of the Art in Localization](https://njsi2019.sched.com/event/T5HA/the-state-of-the-art-in-localization-eemeli-aro-vincit) at the conference, and then staying on to participate in the summit as a voting member of the OpenJS CPC. I'm a maintainer of [messageformat](https://www.npmjs.com/package/messageformat), an OpenJS project.

I'll cover my travel costs from Helsinki otherwise, so am only requesting **880.53 CAD** for four nights' stay at the conference hotel.

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by Trott** [comment]
This needs one more approval from @nodejs/community-committee

**Comment by WaleedAshraf** [comment]
@eemeli I'm not sure (as I'm not speaking), but I thought Foundation already covers the cost of travel and lodging for speakers. But maybe that's not the case. Or maybe, it doesn't matter as one way or other, the Foundation does the reimbursement.

@Trott maybe you can guide here. So that for next time, we can make it better and clear for speakers and collaborators on how and where to ask for travel funds.

@eemeli Also, can you please convert the amount to USD?

**Comment by ladyleet** [comment]
@eemeli pls email me for the registration code for a comped ticket - ladyleet@nodejs.org.

(@WaleedAshraf you have the code now so you can also give it freely privately if that's easier)

**Comment by eemeli** [comment]
@WaleedAshraf I've now updated the amount to **670 USD**. As far as I've understood, this is the recommended path for speakers requesting reimbursement for travel & lodging costs. Sometime in the near future approving these travel requests will move from here to the OpenJS CPC, but as that hasn't happened yet, I submitted mine according to the current instructions.

@ladyleet Thank you for the offer; I've already received a comped ticket as a speaker.

**Comment by WaleedAshraf** [comment]
@eemeli Thanks for the clarification. 👍

**Pull request merged**
