### PR TITLE
Travel fund request for Collab Summit 2018 - Berlin

### PR DESCRIPTION
**Pull request by NickNaso**
Request for travel fund to attend at Collab Summit Spring 2018.

## Travel Fund Request

Travel: € 117
Hotel: € 283
Total: € 400

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by mhdawson** [comment]
@NickNaso can you confirm you are a member of the foundation?

**Comment by NickNaso** [comment]
Yes I am an individual member of the foundation.

**Comment by mhdawson** [comment]
@nodejs/tsc @nodejs/community-committee since its not that far out it would be great to get more reviews/approvals.

**Comment by bnb** [comment]
@mhdawson I think we can probably approve this 👍

**Comment by mhdawson** [comment]
2+ approvers from TSC and commcomm, going to land.

**Comment by mhdawson** [comment]
Landed as 970b238e415c439071d49f625babee4f39c09963

**Pull request closed without merging**
