### PR TITLE
Add travel fund request for Ben Michel - To Spring Collaborators Summit, Berlin DE

### PR DESCRIPTION
**Pull request by obensource**
## Gettin' to the Collaborators Summit! ✈️

**Event**: Node.js Spring Collaborator's Summit
**Event Location**: Berlin, Germany
**Traveling From**: Portland, OR, US
**Doing**: Attending and facilitating Node.js i18n WG breakouts.
**Stipend Size**: $1450

## Stipend Description
* The flight cost will be $1200
* The hotel const will be $250
* Total cost: $1450

## Groups I'll be representing there
* [Community Committee](https://github.com/nodejs/community-committee)
* [i18n Working Group](https://github.com/nodejs/i18n)

## Stoked!
The Collaborator's Summit in Vancouver afforded me the opportunity to get involved doing meaningful work for Node.js. I'm thrilled for the chance to continue that in person with CommComm and our i18n working group! Thank y'all! 🙌

### CODE REVIEW

**Comment by bnb** [comment]
cc @nodejs/community-committee

**Comment by obensource** [comment]
@mhdawson I became an individual Foundation member when I registered for Node.js Interactive in October (made it super easy! 😎)

Thanks everyone! I'm really excited to see y'all there! 🎉🎉🎉

**Comment by hackygolucky** [comment]
@obensource will you resolve the conflicts on this branch and then I'll happily merge

**Comment by obensource** [comment]
@hackygolucky resolved, thanks a mil! 🍻

**Comment by obensource** [comment]
Woop! 🙌 Woop! 🙌 Woop! 🙌

See y'all there! 🎉🎉🎉

**Pull request merged**
