### PR TITLE
Blankspace taming

### PR DESCRIPTION
**Pull request by craftninja**
Corrected some markdown table issues and a typo. No data change!

blocks stretching back and forth

### CODE REVIEW

**Comment by craftninja** [comment]
I'd be glad to add the olde PR links to already merged peeps' data rows if that is helpful, either in this or another (new) PR.

**Comment by Trott** [comment]
Not opposed to this, but for the record, blank spaces were added to make the table readable as raw text (at least with wrapping disabled), although obviously that tends to deteriorate over time. I'd slightly prefer the spaces to be added back in a way that aligns the table again, but this is fine too.

**Comment by Trott** [comment]
(This also points to the probability that a markdown table might not be the best format, but I'm not sure I have a better one to suggest, at least not within the context of our pull request-based workflow.)

**Comment by craftninja** [comment]
@Trott I was referencing the previous years for guidance, and also mild preference for less blankspace... with the thought that maybe this makes it easier for people to keep columns aligned? I'll keep addressing merge conflicts / column misalignments in the interim ✨

**Comment by SofiEstevez** [comment]
@mhdawson @Bamieh tagging you to approve and merge this :)

**Comment by mhdawson** [comment]
I think it needs a rebase after the previous items that have landed

**Comment by craftninja** [comment]
@mhdawson Updated!

**Pull request merged**
