### PR TITLE
@maddhruv travel request for Collab Summit Berlin 2019

### PR DESCRIPTION
**Pull request by maddhruv**
**Event** - Collab Summit Berlin 2019
**Location** - Berlin, Germany
**Traveling From** - Jaipur, INDIA
**Stipend** - $2000 (_may vary_)

#### Groups representing
- @nodejs/website-redesign 
- @nodejs/i18n 

#### Stipend Breakdown
image

/cc @nodejs/community-committee @nodejs/tsc

### CODE REVIEW

**Comment by MylesBorins** [comment]
Do we generally give a stipend for food?

**Comment by maddhruv** [comment]
last time also, I was given a little amount (didnt show the bills as such)

**Comment by Trott** [comment]
This needs two @nodejs/community-committee approvals.

**Comment by maddhruv** [comment]
@Trott
there's no response from any other CommComm member over this
is there any issue with my request or what?
:disappointed:

**Comment by joesepi** [comment]
LGTM. Sorry for delay on my part.

**Comment by maddhruv** [comment]
please approve and merge if this is done

**Comment by maddhruv** [comment]
Thanks a lot to all

**Pull request merged**
