### PR TITLE
doc: update the Code of Conduct to v2.1

### PR DESCRIPTION
**Pull request by RedYetiDev**
This pull request modifies the Code of Conduct, transitioning it from Version 2.0 to Version 2.1. You can find the current Code of Conduct at <https://github.com/EthicalSource/contributor_covenant/blob/release/content/version/2/0/code_of_conduct.md> and the updated version at <https://github.com/EthicalSource/contributor_covenant/blob/release/content/version/2/1/code_of_conduct.md>.

### CODE REVIEW

**Comment by ovflowd** [comment]
Code of Conduct for OpenJS projects is managed by the OpenJS Foundation. So, you need to request this update on the OpenJS Foundation Cross Project Council repository.

**Comment by ovflowd** [comment]
cc @nodejs/tsc please correct me if I'm wrong, but pretty much sure that's the case 🤔

**Comment by ovflowd** [comment]
BTW the repository in question: https://github.com/openjs-foundation/cross-project-council/

**Comment by RedYetiDev** [comment]
> BTW the repository in question: [openjs-foundation/cross-project-council](https://github.com/openjs-foundation/cross-project-council/)

They are already discussing the change AFAICT

**Comment by ovflowd** [comment]
> > BTW the repository in question: [openjs-foundation/cross-project-council](https://github.com/openjs-foundation/cross-project-council/)
> 
> They are already discussing the change AFAICT

I don't recall if we already worked on transitioning to the version 2.1, but this conversation sounds familiar (cc @joesepi)

**Comment by Trott** [comment]
> The OpenJS Foundation manages the Code of Conduct for OpenJS projects. Therefore, you need to request this update on the OpenJS Foundation Cross Project Council repository.

Wha??? https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md Sure enough, it has Node.js info in there. I wonder if we should remove our copy from the admin repo and point there so as to avoid having conflicts between the two docs. @nodejs/tsc

**Comment by ovflowd** [comment]
> > The OpenJS Foundation manages the Code of Conduct for OpenJS projects. Therefore, you need to request this update on the OpenJS Foundation Cross Project Council repository.
> 
> Wha??? [openjs-foundation/cross-project-council@`main`/CODE_OF_CONDUCT.md](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md?rgh-link-date=2024-06-04T19%3A25%3A42Z) Sure enough, it has Node.js info in there. I wonder if we should remove our copy from the admin repo and point there so as to avoid having conflicts between the two docs. @nodejs/tsc

Some surprises are the best :P

**Pull request closed without merging**
