### PR TITLE
travel fund request

### PR DESCRIPTION
**Pull request by ghinks**
collaborator conference travel fund request

### CODE REVIEW

**Comment by MylesBorins** [comment]
@ghinks $8600 seems a significantly higher cost compared to other folks requesting funds. Can you expand more on what that money is being spent on?

**Comment by ghinks** [comment]
sorry folks typo in amount.

**Comment by Trott** [comment]
I'd still request a breakdown of how the number was calculated. I've only found one travel request that didn't do that and it was for a small amount (someone traveling from within Germany to Berlin) and even that probably should have included that information.

This is important because there are things we would decline or be hesitant about reimbursing. And you don't want to find out after you've spent your own money that (for example) the Foundation isn't reimbursing you for JSConf EU registration.

**Comment by ghinks** [comment]
Good to know. I was under the impression that this was just the flight. I'm sure that there are flights under 1800 but I did not see them at first. I was intending to pay the rest for myself hotels + JSConf tickets. Should I update accordingly saw this is the flight and I'm funding the rest myself. If there are any discounts I would appreciate it for JSConfEU.

**Comment by Trott** [comment]
> Good to know. I was under the impression that this was just the flight. I'm sure that there are flights under 1800 but I did not see them at first. I was intending to pay the rest for myself hotels + JSConf tickets. Should I update accordingly saw this is the flight and I'm funding the rest myself. If there are any discounts I would appreciate it for JSConfEU.

Flight + hotel during the summit part of the trip (so, like, 3 nights max) is pretty typical of the requests, I think. In the past, we also had a requirement that people state that their employers will not cover the travel cost if the Foundation doesn't. Looks like that got removed. ¯\\_(ツ)_/¯ But it gives you an idea of the spirit of the thing.

Most people coming from the U.S. look like they requested about $1000 for flights and $600 for hotel. So $1800 is not ludicrous or anything, but it's good to know what you're expecting to get reimbursed for so we can say "no" when someone suggests a Node.js-themed warehouse rave they want to organize on the Foundation's dime.

**Comment by ghinks** [comment]
Stipend calculation. 1660USD airfare (booked)
I'll cover the rest.

**Comment by Trott** [comment]
This needs one more @nodejs/community-committee approval.

**Pull request merged**
