### PR TITLE
doc: add policy around creating teams

### PR DESCRIPTION
**Pull request by MylesBorins**
Refs: https://github.com/nodejs/admin/issues/307

TL;DR same rules as repos

### CODE REVIEW

**Comment by targos** [comment]
I'd prefer to just have to notify without waiting. I don't see why somebody would object to the creation of a team and if there's a problem with the name it can be changed easily.

**Comment by addaleax** [comment]
I’m just going to mention that I when the nodejs org was created, it was intentional that repos could be created without significant process around it. I liked that and I wish we didn’t step further in a different direction (or at least not without providing good reasons to do so, which I don’t think we did when implementing rules around repositories).

**Comment by Trott** [comment]
(@MylesBorins Let me know if I should take free rein to edit the text as I see fit. I don't _think_ I'm changing the meaning or spirit.)

**Comment by MylesBorins** [comment]
@Trott edit away 😄

**Pull request merged**
