### PR TITLE
update travel funds for @waleedashraf

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Updating travel funds according to the plane ticket price.
I think I selected the wrong location when creating PR first time.

Previous Total: $2030
Updated Total: $2400

|  | Cost  |
|------|-----|
| Flight | ~$1020 |
| JS Interactive ticket | $350 |
| Lodging | $650 |
| Visa | ~$180 |
| Misc | ~$200 |
| **Total** | **~$2400** |

Previous PR: https://github.com/nodejs/admin/pull/215

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
Need one more approval from TSC @gibfahn

**Comment by Trott** [comment]
Can you put a breakdown here of the costs? I'm curious what was more expensive than expected. That's the only thing that kept me from approving.

**Comment by WaleedAshraf** [comment]
As I mentioned in details, it's plane ticket price.
@Trott updated.

**Comment by Trott** [comment]
> As I mentioned in details, it's plane ticket price.

Yeah, right in the first sentence. Sorry about that!

**Pull request merged**
