### PR TITLE
travel fund: update final amount for @fishrock123

### PR DESCRIPTION
**Pull request by Fishrock123**
Due to when I booked vs when I submitted, the cost was slightly more than anticipated.

### CODE REVIEW

**Comment by Trott** [comment]
The difference was the airfare or something else?

**Comment by Fishrock123** [comment]
Airfare and train. Also, the transit pass (~$20 cad) I used for the 3 days while I was there.

**Comment by Trott** [comment]
@brianwarner Do the overages need to be broken down into categories like in the original PR. (I'm going to guess the answer is "yes".)

**Comment by brianwarner** [comment]
@Trott I believe that's a decision-making policy question which is upstream from me. I would suggest it yes, though, because the amounts are known after the fact.

**Comment by Trott** [comment]
@Fishrock123 Can you please provide the above-mentioned breakdown? I know the amount here is small, but I wouldn't want to set a bad precedent that results in a future appearance of a double-standard.

**Comment by Fishrock123** [comment]
Taken directly from my Expensify report:

Screen Shot 2020-01-14 at 11 56 54 AM

_(Yes, I booked my train on the 12th. I was certain I did so on the 4th with the rest but I guess it did not actually book correctly.)_

**Comment by Trott** [comment]
Since this is an increase, it's going to need two @nodejs/community-committee reviews. Ping!

**Pull request merged**
