### PR TITLE
Add Travel Fund Request for @SMotaal

### PR DESCRIPTION
**Pull request by SMotaal**
**Event**
   JS Interactive and Collaborator Summit 

**Location**
   Vancouver, British Columbia, Canada

**Date**
   Oct10 thru Oct14

**From**
   Toronto, Canada

| | Estimate USD | Paid CAD | Equivalent USD |
|:-|-:|-:|-:|
| Flight + Hotel (*Expedia*) | $1,500.00 | $1,759.38 | $1,358.09 |
| Registration | $350.00 | — | $350.00 |
| **Total** | $1850.00 | — | $1708.09 |

**Notes**
- Collaborator (used code to register)
- Corporate funding is not available
- ~~Disputing unexplained airline expense for US $291.30 (not included in request)~~ **resolved**

cc @nodejs/tsc and @nodejs/community-committee

### CODE REVIEW

**Comment by MylesBorins** [comment]
I think we are supposed to keep a registration cost of $350 even if you registered with a code.

/cc @ladyleet

**Comment by ladyleet** [comment]
@SMotaal @MylesBorins yep! :) after this gets approved pls email me ladyleet@nodejs.org for the code.

**Comment by SMotaal** [comment]
@ladyleet Should adjust to include this value now?

**Comment by ladyleet** [comment]
@SMotaal yes pls!

**Comment by SofiEstevez** [comment]
Hi @SMotaal ! I'm Sofi from This Dot team, writing on behalf of Node.js Foundation.

I don't see you have send the report for reimbursement on this. (Apologies if you did already, it is possible that this is not updated: https://github.com/nodejs/admin/blob/master/TravelFunds/2018.md )

We just wanted to let you know the last day to ask for this reimbursement is Jan 19th.
After that date, reimbursements for 2018 travels will no longer be available.

Thank you!

**Comment by ladyleet** [comment]
@SMotaal can you send it to travelapprovals@nodejs.org and we'll continue the conversation there?

**Comment by SMotaal** [comment]
@ladyleet done 👍  thanks 😄

**Comment by ladyleet** [comment]
@SMotaal you're the best!

**Comment by SMotaal** [comment]
@ladyleet you are the best 👍 … I just saw the transaction on my statement 😄

**Pull request merged**
