### PR TITLE
Update 2018.md

### PR DESCRIPTION
**Pull request by SofiEstevez**
Hi! I'm from ThisDot, working for Node.js. I edited this with some new updates.

### CODE REVIEW

**Comment by mhdawson** [comment]
This seems to need an update, due to the other PR's that have landed.

**Comment by SofiEstevez** [comment]
@mhdawson Hi! Could you help me merge this? Thx!

**Comment by ChALkeR** [comment]
@nodejs/tsc @SofiEstevez @chowdhurian 
This reverted #241 and decreased my approved amount fro $1660 back to $1500.

Was that intended?

**Comment by ChALkeR** [comment]
This also reverted https://github.com/nodejs/admin/pull/217.
/cc @codeekage -- was that intended?

**Pull request merged**
