### PR TITLE
WIP - doc: allow multiple orgs and add pkgjs org

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/nodejs/admin/issues/470

Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
This is first part of several that are needed for https://github.com/nodejs/admin/issues/470.  Should not land until those have been covered off:

- [ ] Proposed charter for Package Maintenance team which delegates approval of the creation of 
   new repos to that team, addition of members, along with some org owner capability.  I believe this 
   is what the package  maintenance team wants, but need to work through the details.

**Comment by mcollina** [comment]
I think you need to update the onboarding docs for  TSC and CommComm members as they will become org owners.

**Comment by mhdawson** [comment]
@mcollina thanks, will add that to the list.

**Comment by mmarchini** [comment]
One thing I noticed (and don't have a good fix for) is that Node.js members won't be able to ping teams on the pkgjs org. Not sure if that's something we didn't consider or if it was intentional, and unfortunately I don't think there are any workarounds for it, but might be a good thing to add to a "considerations list" or something for folks thinking about spinning up a separate org.

**Comment by dominykas** [comment]
This is a good point. Does github have an issue tracker for things like this? Node/pkgjs is not the only place where I'm missing a sort of "umbrella org" / cross-org teams feature. At a certain point, esp. in the ecosystem of loooooots of small modules, a single org becomes too large to administer. I sure we're not the only ones experiencing this.

**Comment by mmarchini** [comment]
There's a private repo, but it's more for feedback on beta features instead of new features. Sending the suggestion via support might be a good idea.

**Comment by bnb** [comment]
@mhdawson do we want to continue with this?

**Comment by mhdawson** [comment]
@bnb yes, since we already have the second org :)

**Comment by mhdawson** [comment]
@nodejs/tsc any objections to this. If not I'll rebase and submit another PR to update the on/offboarding docs 

@bnb would you be able to check over the moderation docs to see if they need any changes?

**Review by mmarchini — APPROVED** [review]

**Comment by mmarchini** [comment]
should we move the checklist from https://github.com/nodejs/admin/pull/484#issuecomment-604486043 to a new issue to make sure it doesn't get lost?

**Comment by bnb** [comment]
@mhdawson making "Node.js GitHub Organization" be "Node.js GitHub Organizations" in every instance should cover it.

**Comment by mhdawson** [comment]
@bnb 

> making "Node.js GitHub Organization" be "Node.js GitHub Organizations" in every instance should cover it.

Is that something you'd like to do or should I submit a PR to do that?

**Comment by bnb** [comment]
@mhdawson i'm happy to do it in a separate PR, just wasn't sure if you wanted to do it in this one.

**Comment by mhdawson** [comment]
@bnb added the updates to the Moderation-Policy.md and one small PR to the docs in the moderation repo - https://github.com/nodejs/moderation/pull/531 once that lands I think this PR can land.

**Comment by Trott** [comment]
@mhdawson If this is still needed, can you resolve the conflict?

**Comment by mhdawson** [comment]
@Trott, I rebased and will now land.

**Pull request merged**
