### PR TITLE
Add @dshaw to the list of Calendar Maintainers

### PR DESCRIPTION
**Pull request by dshaw**
I have already be granted this privilege. Updating the list for community awareness and visibility.

### CODE REVIEW

**Comment by dshaw** [comment]
This will resolve #96

**Comment by Trott** [comment]
Does @dshaw have permissions to the calendar? If so, time to merge this. If not, then let's fix that...

**Comment by mhdawson** [comment]
The first line says: "I have already be granted this privilege" so I'd say go ahead and merge.

**Comment by Trott** [comment]
> The first line says: "I have already be granted this privilege" so I'd say go ahead and merge.

I would say I didn't read far enough, but... first line.... yeah. OK, merging!

**Pull request merged**
