### PR TITLE
doc: request token for amaro

### PR DESCRIPTION
**Pull request by marco-ippolito**
Should fix: https://github.com/nodejs/amaro/issues/101

```
permissions:
  contents: write
  pull-requests: write
```

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM once the token name and date are filled in.

**Comment by legendecas** [comment]
@marco-ippolito could you name the token?

**Comment by marco-ippolito** [comment]
Does `AMARO_SWC_UPDATE_TOKEN` sound good?

**Comment by legendecas** [comment]
yeah, sounds good. TBH it's up to the owner of the repo.

**Comment by legendecas** [comment]
if it will be used in `release-please` as well, probably name it as like `GH_USER_TOKEN`.

**Comment by marco-ippolito** [comment]
@legendecas I used same name as other ones since it will be used in release plz in the future, set expiration day as if it is created tomorrow. Can I create it myself?

**Comment by legendecas** [comment]
if you have access to @nodejs-github-bot account please feel feel to go ahead.

**Review by jasnell — APPROVED** [review]

**Comment by legendecas** [comment]
I don't have access either. It'd be great to automate this process with https://github.com/nodejs/admin/issues/936, which allow TSC members to grant new access without @nodejs-github-bot's password.

**Comment by mhdawson** [comment]
Generated thet token and set in the amaro repository. @marco-ippolito can you check and land this PR if everything looks ok ?

**Comment by marco-ippolito** [comment]
the token does not have the right permission  https://github.com/nodejs/amaro/issues/101

**Comment by marco-ippolito** [comment]
It's working thanks!

**Pull request merged**
