### PR TITLE
Move travel fund management to the Cross-Project-Council

### PR DESCRIPTION
**Pull request by mcollina**
As titled, this PR moves the management of the travel fund to the cross-project-council.

https://github.com/openjs-foundation/cross-project-council

Ref: https://github.com/openjs-foundation/cross-project-council/pull/441

### CODE REVIEW

**Comment by MylesBorins** [comment]
Could we maybe keep the documents in an archive folder for historical purposes?

**Comment by mcollina** [comment]
> Could we maybe keep the documents in an archive folder for historical purposes?

Done. I've also renamed the folder.

**Comment by WaleedAshraf** [comment]
Needs an update.

**Comment by mcollina** [comment]
@WaleedAshraf done.

**Pull request merged**
