### PR TITLE
Update travel funds for @ryzokuken

### PR DESCRIPTION
**Pull request by ryzokuken**
| Info | Requested | Original | Final | Final (USD) |
|---|---|---|---|---|
| Airfare | $ 1100 | ₹ 75,584 | ₹ 17,925 | $ 246 |
| Lodging | $ 900 | CAD 1,145.63 | CAD 0 | $ 0 |
| Ticket | $ 100 | $ 100 | $ 100 | $ 100 |
| Misc | $ 400 | CAD 100 | CAD 100 | $ 77 |
| Total | $ 2500 | – | – | $ 423 |

### CODE REVIEW

**Comment by ryzokuken** [comment]
@MylesBorins yes, I wasn't. Will update this PR with the conference ticket amount and stuff (basically the minimal things that couldn't be refunded).

**Comment by ryzokuken** [comment]
@MylesBorins done! Sorry for the delay. Had been waiting for the airline to confirm the refund so that I could quote the exact amount here.

/cc @mhdawson @WaleedAshraf @JemBijoux you might want to take another look.

**Comment by ryzokuken** [comment]
Okay, everything seems to have changed. I'll change the appropriate files.

**Comment by ryzokuken** [comment]
Done!

**Comment by ryzokuken** [comment]
Waiting for @mhdawson and @WaleedAshraf to reapprove.

@Trott apart from that I guess this is good to go?

**Comment by Trott** [comment]
> @Trott apart from that I guess this is good to go?

I guess. Given that it's a smaller amount than they originally approved, I won't complain if someone lands it.

**Comment by targos** [comment]
@ryzokuken this PR was approved by 2 TSC and 2 CommComm members. It can be merged.
BTW, I think that we shouldn't require any special approval to lower an already allocated amount.

**Comment by ryzokuken** [comment]
Thanks, @targos, for clarifying. I guess someone from the TSC or CommComm could merge this, then?

**Pull request merged**
