### PR TITLE
chore: update policy to reflect current moderation team membership

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Review by othiym23 — APPROVED** [review]
🚢 LGTM. Thanks for taking care of this, @Trott.

**Comment by nschonni** [comment]
Does it make sense to switch to `ncu-team-sync` like in the build rpo https://github.com/nodejs/build/pull/2657 or is having the emails better?

**Review by bnb — APPROVED** [review]

**Comment by Trott** [comment]
> Does it make sense to switch to `ncu-team-sync` like in the build rpo [nodejs/build#2657](https://github.com/nodejs/build/pull/2657) or is having the emails better?

Email seems possibly important in case people want to contact a moderation team member privately without emailing the entire team. That said, I'm not opposed to switching to `ncu-team-sync` as many of us have our emails publicly available in our GitHub profiles, for example.

**Review by Emciu — COMMENTED** [review]
Ok

**Pull request merged**
