### PR TITLE
add @maddhruv to calendar maintainers

### PR DESCRIPTION
**Pull request by maddhruv**
I shall be maintaining the @nodejs/badges and maybe @nodejs/website-redesign meeting events.
Reducing a much load from @bnb :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by Trott** [comment]
@maddhruv Have you already been given calendar access or is that what we're waiting for before landing this?

**Comment by maddhruv** [comment]
I don't have access to the calendar right now

**Comment by maddhruv** [comment]
I still don't have any access to the calendar! 
@Trott can you look into?

**Comment by Trott** [comment]
> @Trott can you look into?

I don't think I've ever given calendar privileges to anyone before. Maybe @bnb knows how to do it?

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee Anyone know how to the calendar privileges work and feels comfortable extending it to @maddhruv?

**Comment by mhdawson** [comment]
I figured it out and added him :)

**Comment by maddhruv** [comment]
Thanks @mhdawson

**Comment by maddhruv** [comment]
@Trott can this be merged?

**Pull request merged**
