### PR TITLE
Travel fund request for @tniessen for Node + JS Interactive 2019

### PR DESCRIPTION
**Pull request by tniessen**
Travel request for Node + JS Interactive 2019 and Collaborator Summit. I am an individual member of the foundation, contributor, collaborator and TSC member.

Airfare: $500 (estimated)
Hotel: $1000 (five nights at estimated $200/night)
~Conference ticket: $100 (confirmed by @ladyleet)~
Other travel (to/from airport): Estimated $50

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
@ladyleet can you please confirm what's the process of "Conference ticket" cost & reimbursement?

I opened an [issue](https://github.com/nodejs/admin/issues/425) earlier but it seems no one knows how it is this time.
Also, I'm in touch with Celia Stamps (Linux Foundation) about it, and she said there will be a post about complimentary registration.

Which means we don't need to mention the conference ticket price in PRs?

**Comment by tniessen** [comment]
@WaleedAshraf No, I will not. What would be the benefit of doing that?

Feel free to block this PR, that's fine.

**Comment by WaleedAshraf** [comment]
@tniessen If you are fine with the wait, then it's ok.

**Comment by ladyleet** [comment]
> @tniessen
> Can you please remove the cost of the ticket, until we receive a reply from @ladyleet or someone from Linux Foundation on what is the process for tickets for a collaborator. You can update your funds later with the ticket cost if this is the way. I'm asking because I received different information from Celia Stamps. I think organizers are currently working on it and it's not finalized yet.
> 
> Other than that, your PR is fine.

Hey @WaleedAshraf! Thx for checking. I actually just received the code, so for now, those who would like to get the code for attending the conf, they can email me at ladyleet@nodejs.org (@tniessen send me a note and you can remove the $ from this PR?)

**Comment by ladyleet** [comment]
> @ladyleet can you please confirm what's the process of "Conference ticket" cost & reimbursement?
> 
> I opened an [issue](https://github.com/nodejs/admin/issues/425) earlier but it seems no one knows how it is this time.
> Also, I'm in touch with Celia Stamps (Linux Foundation) about it, and she said there will be a post about complimentary registration.
> 
> Which means we don't need to mention the conference ticket price in PRs?

@WaleedAshraf didn't see the issue - I'll go ahead and respond there. Feel free to ping me anytime.

**Pull request merged**
