### PR TITLE
doc: remove section on export control

### PR DESCRIPTION
**Pull request by mhdawson**
Signed-off-by: Michael Dawson <mdawson@devrus.com>

This is long out of date and I've been told that the OpenJS foundation has new/different processes for handling this through the Linux Foundation.

### CODE REVIEW

**Comment by mhdawson** [comment]
@jorydotcom,  @brianwarner FYI.

**Comment by mhdawson** [comment]
@nodejs/tsc, @nodejs/community-committee would be good to get some reviews so that this can land.

**Comment by mmarchini** [comment]
> the OpenJS foundation has new/different processes for handling this through the Linux Foundation

Care to elaborate? It might help folks get peace of mind to approve the PR.

**Comment by mhdawson** [comment]
@mmarchini I don't have the details @brianwarner might, but at this point the doc we have is long out of date so wanted to remove  it.

**Comment by bnb** [comment]
Happy to review pending @mmarchini's request for context

**Review by mcollina — APPROVED** [review]
lgtm

**Review by bnb — APPROVED** [review]

**Review by joesepi — APPROVED** [review]

**Comment by mhdawson** [comment]
@brianwarner, @jorydotcom people have asked that at least one of you sign off on this before they are comfortable that we remove it.

**Comment by brianwarner** [comment]
Yep, looks fine, this is replaced by https://openjsf.org/export.

**Review by brianwarner — APPROVED** [review]

**Review by BethGriggs — APPROVED** [review]

**Comment by mhdawson** [comment]
k, we have 2 TSC and 2 CommComm approvals now so I'm going to land.

**Pull request merged**
