### PR TITLE
remove unnecessary qualifier in moderation policy

### PR DESCRIPTION
**Pull request by Trott**
IMO, "considered" introduces ambiguity. Let's be clear.

### CODE REVIEW

**Comment by Trott** [comment]
@nodejs/moderation @nodejs/tsc

**Review by cjihrig — APPROVED** [review]

**Review by targos — APPROVED** [review]

**Review by jasnell — APPROVED** [review]

**Review by aduh95 — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by JohnTitor — APPROVED** [review]

**Review by gireeshpunathil — APPROVED** [review]

**Review by RaisinTen — APPROVED** [review]

**Review by XProudfootX — COMMENTED** [review]
Cool

**Comment by Trott** [comment]
> XProudfootX

User blocked.

https://github.com/nodejs/admin/pull/682#pullrequestreview-2813199799
https://github.com/nodejs/.github/pull/33#pullrequestreview-2813198437
https://github.com/nodejs/admin/pull/767#pullrequestreview-2813201354

**Pull request merged**
