### PR TITLE
Travel sponsorship request for @davisjam

### PR DESCRIPTION
**Pull request by davisjam**

### CODE REVIEW

**Comment by Trott** [comment]
@davisjam Can you provide a breakdown for your estimate? How much is airfare, how much is hotel, etc.?

@nodejs/tsc @nodejs/community-committee

**Comment by davisjam** [comment]
Airfare: $700.
JS Interactive registration: $700 (unless I can still get the early-bird price somehow?).
Some support towards housing and food: $100.

I think my PhD advisor can help out a little bit with the rest of the cost of housing and food.

**Comment by targos** [comment]
There is special registration price of $100 for academics.

**Comment by davisjam** [comment]
Thanks @targos.

New breakdown:

| Item | Cost |
|-----|-------|
| Airfare | $700 |
| JS Interactive Registration | $100 |
| Towards food and housing | $375 |
|------|-------|
| Total request | $1175 |

**Comment by Trott** [comment]
@ladyleet I know you may not have an answer yet but if/when you do: Should people who are able to get academic pricing for tickets like this still *not* buy their tickets but include the price in their travel request? And if so, which price? /cc @joyeecheung

**Comment by Trott** [comment]
(Needs to be open for 72 hours, and still requires two CommComm approvals.)

**Comment by Bamieh** [comment]
I have no objection to this at all **but** I thought it was agreed not to include the price of tickets in these funds

**Comment by Trott** [comment]
> I have no objection to this at all but I thought it was agreed not to include the price of tickets in these funds

@Bamieh Yeah, I'm a bit confused on this too. Hopefully @ladyleet and/or @joyeecheung and/or Annmarie can clear this up, but as best as I understand, a flat ticket price (of $350 I think?) should be included (for some folks? all folks?) as the money does get deducted from the travel fund but the requester shouldn't buy the tickets themselves. I could be wrong about this, which I almost hope I am because it is probably going to continue to be a source of confusion if people are supposed to ask for funds that they're then not supposed to use. (Likely a non-zero number of them will go buy a ticket and then expect to be reimbursed for it.)

**Comment by ladyleet** [comment]
@Trott anyone who can get academic pricing should purchase their ticket and submit the receipt for reimbursement. we will only provide codes for the $350 special pricing. :) 

$350 flat ticket pricing should be included to anyone who needs their ticket covered and cannot get a better deal (ie $100 academic).

We have almost finalized how ticket distribution to those requesting funding at the $350 rate will occur so hold tight! I should have a final method this week.

Hope this helps clear up some confusion? If not lmk and I'll elaborate.

**Comment by cjihrig** [comment]
I think the Foundation has already burned through it's cough drop budget for the year. Other than that, LGTM.

(joking: the whole thing LGTM)

**Comment by jasnell** [comment]
Lgtm

**Comment by WaleedAshraf** [comment]
LGTM

**Comment by thefourtheye** [comment]
LGTM

**Pull request merged**
