### PR TITLE
Self Nominate Larson Carter - Social Media Team

### PR DESCRIPTION
**Pull request by larson-carter**
Hello All!

I'm self nominating myself for the social media team!

I'm ridiculously active on Twitter + LinkedIn. I would like to help out there as much as possible.

I love promoting projects and making announcements. I work best with at least 1 other person all the way up to a team. If @bnb wouldn't mind I would like to work alongside him.

Thank You!

### CODE REVIEW

**Comment by mcollina** [comment]
Hi Larson, thanks for passing by. I did a quick search on this org and I could not find you as a member, but maybe I’m mistaken.

Being our voice on social media takes a great responsibility, so we give them to folks we know and trust. I would recommend you to participate to https://github.com/nodejs/community-committee before asking for responsibilities.

**Comment by larson-carter** [comment]
@mcollina 

Right I am not a member of the org. Is there a process to becoming a member? If so I would like to apply or do anything that requires.

**> Being our voice on social media takes a great responsibility, so we give them to folks we know and trust.**
I completely understand!

**> I would recommend you to participate to https://github.com/nodejs/community-committee before asking for responsibilities.**
By participating, do you mean applying to become a member? I've thought about doing so, I just didn't know if that was the right direction to getting involved.

Thank You!

**Comment by devsnek** [comment]
@larson-carter you don't need to be a member to help out, check out https://github.com/nodejs/community-committee#contributing

**Comment by larson-carter** [comment]
@devsnek Thank you. Just curious what is the process of becoming a member of the org? I'm definitely going to start going to the meetings.

**Comment by devsnek** [comment]
@larson-carter just be active and constructive. it depends on the specific working group, but membership is generally more about project stewardship. lack of it won't block you from being able to contribute your code, ideas, etc.

**Comment by larson-carter** [comment]
@devsnek Awesome, thank you for putting up with all of my questions!

**Pull request closed without merging**
