### PR TITLE
Update travel-visas doc

### PR DESCRIPTION
**Pull request by WaleedAshraf**
As discussed in last CommComm meetings, adding emails for further assistance.

Related to: https://github.com/nodejs/admin/issues/239

### CODE REVIEW

**Comment by ZibbyKeaton** [comment]
Looks good to me. I approved this.

**Comment by WaleedAshraf** [comment]
On hold for now.
Will update with VISA email address.

**Comment by keywordnew** [comment]
Zibby's email needs to be updated :)

And the label removed.

**Comment by keywordnew** [comment]
Super! Thanks Waleed 👍🏽

**Pull request merged**
