### PR TITLE
Node+JSI travel fund sponsorship request for @dshaw

### PR DESCRIPTION
**Pull request by dshaw**
Event: Node+JS Interactive + Node.js Collaborator Summit
Location: Vancouver BC, Canada
Traveling from: San Francisco, CA

|  | Cost  |
|------|-----|
| Flight | $520 |
| Lodging | $1300 |
| **Total** | **$1820** |

I am an individual member of Node.js Foundation.
Corporate funding is not available.

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by dshaw** [comment]
**Final Amount**

|  | Cost  |
|------|-----|
| Flight | $519.28 |
| Lodging | $1,013.84 |
| **Total** | **$1,533.12** |

**Comment by dshaw** [comment]
@Trott Do you have any recommendations as to how to fix this PR? The content this PRs against has moved to another document: https://github.com/nodejs/admin/blob/master/TravelFunds/2018.md

**Comment by Trott** [comment]
@dshaw Fixed it for you (I think--I find the table in the new document unwieldy to edit by hand.)

**Comment by JemBijoux** [comment]
Thanks @Trott, that fixes that. Let's get this merged.

**Pull request merged**
