### PR TITLE
Update 2018.md

### PR DESCRIPTION
**Pull request by SofiEstevez**
Updated the travel fund with dates of reports sent in rows 31 and 32.

### CODE REVIEW

**Comment by ladyleet** [comment]
thanks @SofiEstevez !

**Comment by ladyleet** [comment]
@chowdhurian @WaleedAshraf care to review this and approve as well?

**Comment by WaleedAshraf** [comment]
@SofiEstevez some conflicts showed up.

**Comment by SofiEstevez** [comment]
Thanks so much for helping me! Hope is all good now @WaleedAshraf  @mhdawson

**Pull request merged**
