### PR TITLE
Request for Travel Reimbursement

### PR DESCRIPTION
**Pull request by patriciarealini**
Event: Node Summit
Dates: July 23-25, 2018
Location: San Francisco, CA, USA
Traveling from: Los Angeles, CA, USA

I am speaking on the Building Node.JS and Javascript Communities Panel. 

@nodejs/community-committee

Travel (Gas) : $150
Lodging: $1000

### CODE REVIEW

**Comment by hackygolucky** [comment]
cc @nodejs/tsc for two +1s, por favor. Already confirmed with @patriciarealini she is an active Individual Member.

**Comment by Trott** [comment]
This is for NodeSummit and not JS Interactive. (Just in case people aren't reading closely and have opinions.)

**Comment by Trott** [comment]
So, I'm neutral on using travel funds for stuff like this. I suspect everyone else is either neutral or for it, but since I've been wrong in those estimations before....

Here's how this request is different from most others.

It's for NodeSummit, not a Foundation event. There's precedence for doing stuff like this with travel funds, but I wouldn't be surprised if we want to ask more questions on these kinds of requests. Specific things that come to mind:

* Confirm that the requester is an individual member of the Foundation. (I believe that's a hard requirement from the Board, so we have no wiggle room on it. The fund is for individual members only.)

* Was NodeSummit already asked to pay for this and declined? If not, can we ask them first?

* Is it reasonable to ask the individual's employer to pay for this? If so, have we done that first?

Again, I'm neutral on this. I just don't want to flag it for people who care about these things and so that it doesn't accidentally set a precedent we don't want to set.

This PR needs to stay open for 72 hours total before it can be merged and the request can be considered approved, so folks have another 42 hours or so to raise concerns, if anyone has any.

**Comment by Trott** [comment]
(Oh, for the record, the first thing about being an individual member, that's a formality if you're a Node.js contributor, since membership is free. Check out the README in the https://github.com/nodejs/members repo if you're not sure if you're a member or not.)

**Comment by mhdawson** [comment]
@Trott  @hackygolucky already confirm individual membership in https://github.com/nodejs/admin/pull/182#issuecomment-406035304

**Comment by patriciarealini** [comment]
@Trott 

`It's for NodeSummit, not a Foundation event. There's precedence for doing stuff like this with travel funds, but I wouldn't be surprised if we want to ask more questions on these kinds of requests.`

It seems to me then that this is a separate issue. Since there is already precedence, then any additional requirements should be proposed as an amendment to the existing requirements for applying to the travel fund and then that line of questioning should be agreed upon among commcomm & TSC admins. This is moving the goalposts. 
Furthermore, I was asked by @bnb, a Node commcomm member, to speak on this panel. I agreed to do so because I was assured that my individual membership with Node Foundation and my status as a contributor made me eligible for reimbursement for the travel. 

In regards to the specifics...

`Confirm that the requester is an individual member of the Foundation. (I believe that's a hard requirement from the Board, so we have no wiggle room on it. The fund is for individual members only.)`
I am an individual member. Confirmation from @hackygolucky of this fact precedes your line of questioning. It is already listed as a requirement in the MEMBER_TRAVEL_FUND.md file.

`Was NodeSummit already asked to pay for this and declined? If not, can we ask them first?`
Node Summit does not pay for panelist accommodations, only speakers. 

`Is it reasonable to ask the individual's employer to pay for this? If so, have we done that first?`
I am currently unemployed. 

I would like it noted that the Member Travel Fund was established to help make geographically based events more accessible to Node contributors and especially under represented members of the Node community and no where does it limit the type of event or say that preference is given to Foundation hosted events. ["Preference given to underserved communities. More specifically, within a subject the foundation is trying to promote awareness about (e.g. general knowledge about the foundation) there are people, communities, and geographies where that knowledge is not very widespread." quoted directly from admin/MEMBER_TRAVEL_FUND.md]

**Comment by jasnell** [comment]
Fwiw, the travel fund was never intended to only cover foundation events.

**Comment by Trott** [comment]
> Fwiw, the travel fund was never intended to only cover foundation events.

Right. Just to be clear (and I'm not sure if this is your impression or not, but it's probably the impression of *some* folks): I never said that was the intention, nor as far as I can tell has anyone else. All I said was that for non-Foundation events, we may want to ask more questions. That can be debated, but it is a judgment call. The administration of the travel fund is left to the judgment of the TSC and CommComm. The way I said this landed badly, clearly, and I regret that. But I stand by the otherwise bland position.

**Pull request merged**
