### PR TITLE
travel fund request: @devsnek for webassembly summit

### PR DESCRIPTION
**Pull request by devsnek**
Airfare: $120
Hotel: $280

### CODE REVIEW

**Comment by Trott** [comment]
I believe the Node.js travel fund expires at the end of 2019 and there will be a CPC travel fund replacing it for 2020. Ultimately, the travel fund fate is up to the OpenJS Foundation board, I believe. Or maybe the CPC? Either way: /ping @MylesBorins @mhdawson This probably needs to be resolved relatively quickly?

**Comment by MylesBorins** [comment]
I think we can approve this and attempt to have it come from 2019 budget if expense comes in before eoy

Either way it shouldn't be controversial for this to move forward if we approve it imho

**Comment by mhdawson** [comment]
I talked to the board and sounds like the budget will be firmed up around the 20th of this month.  I'll ask for a quick approval on this as a one-off

**Comment by devsnek** [comment]
@mhdawson thank you!

**Comment by Trott** [comment]
It's not clear to me if this is going to go through a new process after the 20th or if we should approve it with the old process. If the latter, this needs two @nodejs/community-committee approvals.

**Comment by mhdawson** [comment]
@Trott I've requested a Board vote to get the ok for funds as a one-off for this. I suggest we follow the old process until https://github.com/openjs-foundation/cross-project-council/pull/441 unless other CPC members feel differently.  

Once we get the board approval, I'll add my approval which can count as one of the CommComm approvals and then we can work to get the second.

**Comment by mhdawson** [comment]
Board has approved as a one off.  @devsnek sorry if it too a bit of time.

**Comment by mhdawson** [comment]
Will try to round up second @nodejs/community-committee approver

**Comment by devsnek** [comment]
@mhdawson no worries, thank you very much

**Pull request merged**
