### PR TITLE
Travel fund request for JS Interactive/Collab Summit 2018

### PR DESCRIPTION
**Pull request by inidaname**
Event: JS Interactive + Collaborator Summit
Location: Vancouver BC CAN
Traveling from: Abuja, Nigeria

In addition to participating in Collaborator Summit.
@nodejs/modules

Airline: $1900
Lodging: $400
Visa Fee: $76
Total: $2376

### CODE REVIEW

**Comment by Trott** [comment]
Will you need a visa to go to Canada? If so, you can include those expenses if you wish.

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by inidaname** [comment]
@Trott I edited the total sum and added the Visa application price. 
👍

**Comment by Trott** [comment]
Still LGTM.

This will need 1 more approval from @nodejs/tsc and 2 approvals from @nodejs/community-committee. (It will also need to be open 72 hours to allow for anyone objecting, although objections are very unusual.)

**Pull request merged**
