### PR TITLE
Revise amount from 2018 request

### PR DESCRIPTION
**Pull request by devsnek**
/cc @brianwarner

### CODE REVIEW

**Comment by devsnek** [comment]
@WaleedAshraf the specific differences were sent to brian, but the increase came from underestimating the cost of travel between my hotel and the meeting location.

**Comment by brianwarner** [comment]
Is this ready to merge?  When it goes in, I'll process the reimbursement for @devsnek

**Comment by WaleedAshraf** [comment]
@devsnek there is still duplicate entry. 👀

**Comment by Trott** [comment]
@SofiEstevez Are you who @devsnek could talk to about getting reimbursed? He says he's still waiting on this one.

**Comment by brianwarner** [comment]
I'm the right one, we were just waiting for this pull request to be merged, so now it can go through.

In general though, in order for a reimbursement to go through the travel must already be complete (not an issue here) and the amount approved in the reimbursement file must match what is being requested (which was just addressed a few minutes ago).

**Pull request merged**
