### PR TITLE
Travel Fund: Ben Michel–Node.js Collaborator at MSBuild

### PR DESCRIPTION
**Pull request by obensource**
## Description
I realize this travel fund request is being made retroactively–my apologies. I'm not sure what our policy is around that, but I thought I'd go ahead and make the request anyway after paying out of pocket for travel and lodging. In any case, I understand if my request is approved or denied (I'm extremely thankful for the recent opportunity I had to represent Node.js and CommComm at MSBuild regardless). Y'all are awesome. ❤️

## Travel Fund Request
* **Travel**: $52
* **Hotel**: $350
* **Total**: $402

Thank you, truly! 🙌

### CODE REVIEW

**Comment by bnb** [comment]
After reviewing the travel fund, I don't _see_ a mention of this kind of PR being submitted within a window prior to the event 🤔

Based on that and the fact that this travel and attendance was entirely for Node.js, I'm leaning toward approving this.

**Comment by Trott** [comment]
I don't have a problem with this, but I guess we should probably say explicitly that if the Foundation has a problem with it, then that overrides our approval. (I'm speaking my own opinion here. Others can feel free to disagree of course.) Might be a good idea to find out from @mrhinkle if there are any issues with reimbursing this far after the event. There might be subtle things, like tax implications for the Foundation, that may make this something we want to avoid.

Again, though, I don't have a problem with it myself. Just want to be clear that other issues may come up that are beyond our control that make this something we can't do.

**Comment by WaleedAshraf** [comment]
Whatever is the final decision here, I think we should add instructions in [MEMBER_TRAVEL_FUND](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md) for such case.
Even after that, people can still open an issue to discuss if needed.

**Comment by Trott** [comment]
Needs a rebase.

**Comment by Trott** [comment]
This needs one more @nodejs/tsc approval.

**Comment by Trott** [comment]
This was approved but going forward, retroactive requests will not be honored. (Putting this here for future folks coming across it more than for OP or anything like that.)

**Pull request merged**
