### PR TITLE
update Dhruv Jain @maddhruv fund request

### PR DESCRIPTION
**Pull request by maddhruv**
#### Follows - 
| Info | Amount |
| --- | --- |
| Air Ticket | 1200 |
| Lodging | 700 |
| Visa | 77 |
| Ticket (JSI) | 350 |
| Misc | 300 | 
| **Total** | 2627 |

* all figures in USD

/cc @nodejs/community-committee @nodejs/tsc 
Please merge as early as possible, need to register for JSI and get the VISA. :pray: :pray: :pray:

### CODE REVIEW

**Comment by ChALkeR** [comment]
> Total	2000

Should be 2200, I guess. That's what the diff says and that's what 1000+550+350+300 sum up to.

**Comment by maddhruv** [comment]
@ChALkeR oops my fault! fixed! :face_with_head_bandage:

**Comment by maddhruv** [comment]
@Trott @mhdawson can be merged?

**Comment by Trott** [comment]
> I've always taken this to mean that we'd leave the PR open for a minimum of 72 hours? (Somebody let me know if this isn't the case though...)

Yes, that's correct. It's less clear about adjustments like this, but I'd be inclined to leave it open for 72 hours unless it's a decrease in the amount of the request. Objections are extremely rare (perhaps have never happened?) but we want to give people who might have them adequate time to notice the request.

**Pull request merged**
