### PR TITLE
remove tracy hinds from contact list

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by oe** [comment]
duplicate of #87

**Comment by Trott** [comment]
> duplicate of #87 

This one also removes Tracy. But yeah, I'll remove the duplicate part.

**Comment by Trott** [comment]
Duplication removed. This now just removes Tracy from the list.

**Comment by hackygolucky** [comment]
Soo, this sort of brings up the question of what this list was for @Trott .  At its launch, the list was just the group of people working on this collaboration of top-level committees.  

Yes, I'm no longer an employee of the Node.js Foundation. I am currently the Chair of the Subcommittee Leadership group and as such am still happy to assist on the admin work(and can regardless of being listed here anyway). 

Thoughts anyone? Wondering if that should be a separate issue or conversation?

**Comment by bnb** [comment]
As long as @hackygolucky is willing to work on this repo, I don't really see a conflict with having her listed there - especially not given the heading of that section. Even though @hackygolucky is no longer an employee of the Foundation, she is probably _still_ one of the most experienced people in the subject.

**Comment by Trott** [comment]
Thanks everyone. Closing without landing/merging.

**Pull request closed without merging**
