### PR TITLE
travel request for Berlin (apapirovski)

### PR DESCRIPTION
**Pull request by apapirovski**
## Collab Summit Travel

**Event**: Node.js Spring Collaborator's Summit
**Event Location**: Berlin, Germany
**Traveling From**: San Francisco CA US
**Doing**: Attending
**Stipend Size**: $1600

## Stipend Description
* The flight cost is $800-1000
* The hotel cost will be $500-600
* Total cost (max): $1600

## Groups I'll be representing there
* [TSC](https://github.com/nodejs/tsc)

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by MylesBorins** [comment]
tiny nit... would it make sense to put the update to the chart layout in a separate commit

**Comment by apapirovski** [comment]
@MylesBorins addressed

**Comment by SofiEstevez** [comment]
@mhdawson could we merge this? I think is ready :)

**Comment by Trott** [comment]
> @mhdawson could we merge this? I think is ready :)

This should not have been merged. It was not open long enough.
https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#approval

**Comment by Trott** [comment]
> > @mhdawson could we merge this? I think is ready :)
> 
> This should not have been merged. It was not open long enough.
> https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#approval

(I mean, not that it's really that big a deal. It seems unlikely that someone is going to come along and oppose this. But stuff is supposed to be left open for 72 hours just in case. But you know, next time!)

**Pull request merged**
