### PR TITLE
add moderation team to member expectations

### PR DESCRIPTION
**Pull request by Trott**
The moderation policy indicates that member expectations apply to
moderation team, but the member expectations document only specifies
TSC. Add moderation team.

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by Trott** [comment]
@nodejs/moderation (FYI on this one more than anything else)

**Review by JohnTitor — APPROVED** [review]

**Review by bnb — APPROVED** [review]
I assumed (and thought it was documented!) that this was already the case. Huge +1.

**Comment by Trott** [comment]
> I assumed (and thought it was documented!) that this was already the case. Huge +1.

FWIW, you are right that it is already documented. It's documented in the moderation policy but not in the member expectations document, which only mentions the TSC. This aligns the two documents.

**Review by richardlau — APPROVED** [review]

**Pull request merged**
