### PR TITLE
refack stipend request

### PR DESCRIPTION
**Pull request by refack**
As I'm precluded from traveling to any of the official NF events, and in accordance with the fund's by-laws, I would like to request a stipend for the procurement of hardware.

Stipend Breakdown
Decent desktop computer: US $2300 - https://www.microcenter.com/product/602130/pro-gaming-desktop-mct004

### CODE REVIEW

**Comment by joyeecheung** [comment]
I am confused, this is requesting a stipend for hardware from...travel funds?

**Comment by refack** [comment]
I was refereed here my @mikeal, who claims this was one of the objectives of the fund.
(https://mobile.twitter.com/mikeal/status/901154685997821952)

> sets a problematic precedent.

IIUC each Collaborator's request is evaluated based on it's merit so requests should be approved or rejected independent of precedent.

For context, as I stated in the OP I'm precluded from traveling to any of the NF conferences, so effectively I'm excluded from access to the discretionary fund.

**Comment by Trott** [comment]
> I was refereed here my @mikeal, who claims this was one of the objectives of the fund.

I don't think @mikeal was referring to the travel fund. That tweet suggests a request to the Foundation for a stipend. This is a request to the TSC and CommComm for travel fund money. Those are different things.

**Comment by joyeecheung** [comment]
Maybe this is a new initiative that can be pursued under the new foundation? But then we have not even figure out how the travel fund is going to be managed under the new foundation yet..(I don't even know if that's going to be Node.js's travel fund or a cross-project travel fund)

**Comment by Trott** [comment]
Please re-open (or comment) if anyone believes this is not close-able at this point. Thanks.

**Pull request closed without merging**
