### PR TITLE
chore: fix spacing in `Moderation-Policy.md`

### PR DESCRIPTION
**Pull request by aduh95**
Whitespace change to make the raw file more readable – shouldn't affect the generated HTML.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Isn't this generated by some sort of automated tool?

**Comment by aduh95** [comment]
> Isn't this generated by some sort of automated tool?

Not that I know of

**Comment by Trott** [comment]
> > Isn't this generated by some sort of automated tool?
> 
> Not that I know of

`node-core-utils` has a function to generate lists like this from team memberships. So we could implement that here if we want to although it might result in a slightly different list format. https://github.com/nodejs/node-core-utils/blob/main/docs/ncu-team.md#synchronize-files-with-special-blocks

**Pull request merged**
