### PR TITLE
Travel Fund request: @iansu for Node + JS Interactive 2019

### PR DESCRIPTION
**Pull request by iansu**
## Participating in the Collaborator Summit, 2019
**Event**: Collaborator Summit, Montreal 2019
**Event Location**: Montreal QC, Canada
**Traveling From**: Calgary, AB, Canada
**Doing**: Facilitating Tooling Group meeting and participating in Node + JS Interactive and Collaborator Summit.
Stipend Size: CAD $1649.39
Foundation member: Yes
Corporate travel fund: None

## Stipend Description
Item | Amount | Notes
-- | -- | --
Flight | CAD 548.73 |  
Accommodations | CAD 1100.66 |  
Total | CAD 1649.39

## Groups I'll be representing there
@nodejs/tooling 

## Ping
@nodejs/community-committee @nodejs/tsc

## Why
Travel request for Collaborator Summit, Montreal 2019 at Node + JS Interactive 2019.

### CODE REVIEW

**Comment by tniessen** [comment]
Do we generally reimburse multiple nights before / after the event? It makes sense if it reduces the total cost (e.g., if the difference in flight cost outweighs the cost of accomodations), but I would like to know if we have any official policy.

**Comment by iansu** [comment]
I booked this before I knew I could (potentially) be reimbursed from the travel fund. Happy to adjust the amount.

**Comment by Trott** [comment]
I don't think we have any explicit rule that we don't pay for accommodations beyond what would be necessary to attend the event, but I do believe that has been our practice and a sort of unspoken assumption. It makes sense to me, but of course, there are 30-ish other people on TSC and CommComm and I'm only one opinion.

**Comment by iansu** [comment]
That's perfectly reasonable. I've updated my request and removed one night's accommodation.

**Comment by Trott** [comment]
/ping @nodejs/tsc @nodejs/community-committee This needs some reviews. It's been open for 5 days. 

Especially pinging people on the Tooling group: @bnb @mcollina

**Comment by boneskull** [comment]
github’s iOS app won’t let me review anything, so :+1: 

tooling group needs Ian

**Pull request merged**
