### PR TITLE
Travel fund request for Yadong Ouyang COSCon 2019

### PR DESCRIPTION
**Pull request by oyyd**
Travel fund request for Yadong Ouyang for COSCon 2019 (as C+L mentor) in Shanghai, China.

Airfare: $300 (estimated, Xiamen -> Shanghai & Shanghai -> Xiamen)
Hotel: $100 (1 night, estimated)

Total: $400 (estimated)

@nodejs/tsc @nodejs/community-committee

### CODE REVIEW

**Comment by Trott** [comment]
This still needs one more approval from @nodejs/community-committee (and about 19 more hours too).

**Comment by Trott** [comment]
Re-ping @nodejs/community-committee: This still requires one more approval from CommComm. (It also needs about another 4 hours before it can land.)

**Comment by Trott** [comment]
> (It also needs about another 4 hours before it can land.)

My mistake. It actually needed more than that. Currently needs 11 hours or so. But it has all the approvals it needs and can land except in the unlikely (unprecedented, even?) case of someone on TSC or CommComm opposing it between now and then.

**Comment by gireeshpunathil** [comment]
Landing this now as we have the necessary approvals (invoking @mhdawson 's membership in @nodejs/community-committee ) , and crossing the wait period.

**Comment by gireeshpunathil** [comment]
landed as f412db3f3dd8a5f7a668ecc068abe32e87dd50cd

**Pull request closed without merging**
